### ISSUE TITLE
utf7 does not work in node verson >=6.0.0

### ISSUE THREAD

**Issue by truebit** [kkaefer/utf7#3]
> $ node
> \> var u=require('utf7').imap;
> undefined
> \> u.encode('你好')
> **Error: If encoding is specified then the first argument must be a string**
>     at new Buffer (buffer.js:106:13)
>     at encode (/usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/utf7/utf7.js:4:13)
>     at /usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/utf7/utf7.js:77:39
>     at RegExp.[Symbol.replace] (native)
>     at String.replace (native)
>     at Object.exports.imap.encode (/usr/local/lib/node_modules/appium/node_modules/appium-selendroid-driver/node_modules/utf7/utf7.js:75:36)
>     at repl:1:3
>     at REPLServer.defaultEval (repl.js:272:27)
>     at bound (domain.js:280:14)
>     at REPLServer.runBound [as eval] (domain.js:293:12)
> \>

**Comment by bengotow** [comment]
Just got bit by this issue as well. https://github.com/kkaefer/utf7/pull/4/files looks ok - maybe merge and publish an update?

**Comment by ahelmberger** [comment]
Me too, would be glad if we could get this PR merged. Thanks.

**Comment by mnpenner** [comment]
I'm seeing the same issue when I try with the node REPL, but it actually seems to be working fine within my map. My string is coming from Express header. Tested in Node 6.4.0.

```js
const utf7 = require('utf7');
...
let requestedName = req.get('X-WOPI-RequestedName');
console.log(requestedName); // Jyv+AOQ-skyl+AOQ-
requestedName = utf7.decode(requestedName);
console.log(requestedName); // Jyväskylä
```

Not sure if this is helpful info, but I thought I'd chime in.

**Comment by kkaefer** [comment]
Fixed in https://github.com/kkaefer/utf7/pull/4
